I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script call
    call neg1
  File "game/sxA15.rpy", line 237, in script
    jump game14
ScriptError: could not find label 'game14'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script call
    call neg1
  File "game/sxA15.rpy", line 237, in script
    jump game14
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\student\Desktop\Applications\renpy-8.0.1-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'game14'.

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.1.22070801
AAA 0.0.2.5.7
Tue Nov 29 18:38:38 2022
